name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4
      
      - name: Configura Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Installa le dipendenze
        run: npm install
        
      - name: Compila il progetto
        run: npx vite build
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Carica gli artefatti di build
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Esegui deploy su GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
